//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace oszimt.drive4ever
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Fragen
    {
        public int P_Fragen_ID { get; set; }
        public string Frage { get; set; }
        public string AntwortA { get; set; }
        public string AntwortB { get; set; }
        public string AntwortC { get; set; }
        public string AntwortD { get; set; }
        public string Loesung { get; set; }
    }
}
